version: '3'

services:
  haproxy1:
    image: haproxytech/haproxy-ubuntu:latest
    ports:
      - "8080:80"
    volumes:
      - ./config/haproxy1.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    networks:
      - haproxy_network

  haproxy2:
    image: haproxytech/haproxy-ubuntu:latest
    ports:
      - "8081:80"
      - "15555:5555"
    volumes:
      - ./config/haproxy2.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    networks:
      - haproxy_network

  nginx1:
    image: nginx:latest
    ports:
      - "9080:80"
      - "25555:5555"
    #volumes:
    #  - ./config/haproxy1.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_network

  nginx2:
    image: nginx:latest
    ports:
      - "9081:80"
    #volumes:
    #  - ./config/haproxy2.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_network      

networks:
  haproxy_network:
    driver: bridge
