/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GlobalTuneOptions struct {
	BuffersLimit int32 `json:"buffers_limit,omitempty"`
	BuffersReserve int32 `json:"buffers_reserve,omitempty"`
	Bufsize int32 `json:"bufsize,omitempty"`
	CompMaxlevel int32 `json:"comp_maxlevel,omitempty"`
	DisableZeroCopyForwarding bool `json:"disable_zero_copy_forwarding,omitempty"`
	EventsMaxEventsAtOnce int32 `json:"events_max_events_at_once,omitempty"`
	FailAlloc bool `json:"fail_alloc,omitempty"`
	FdEdgeTriggered string `json:"fd_edge_triggered,omitempty"`
	H1ZeroCopyFwdRecv string `json:"h1_zero_copy_fwd_recv,omitempty"`
	H1ZeroCopyFwdSend string `json:"h1_zero_copy_fwd_send,omitempty"`
	H2BeInitialWindowSize int32 `json:"h2_be_initial_window_size,omitempty"`
	H2BeMaxConcurrentStreams int32 `json:"h2_be_max_concurrent_streams,omitempty"`
	H2FeInitialWindowSize int32 `json:"h2_fe_initial_window_size,omitempty"`
	H2FeMaxConcurrentStreams int32 `json:"h2_fe_max_concurrent_streams,omitempty"`
	H2HeaderTableSize int32 `json:"h2_header_table_size,omitempty"`
	H2InitialWindowSize int32 `json:"h2_initial_window_size,omitempty"`
	H2MaxConcurrentStreams int32 `json:"h2_max_concurrent_streams,omitempty"`
	H2MaxFrameSize int32 `json:"h2_max_frame_size,omitempty"`
	H2ZeroCopyFwdSend string `json:"h2_zero_copy_fwd_send,omitempty"`
	HttpCookielen int32 `json:"http_cookielen,omitempty"`
	HttpLogurilen int32 `json:"http_logurilen,omitempty"`
	HttpMaxhdr int32 `json:"http_maxhdr,omitempty"`
	IdlePoolShared string `json:"idle_pool_shared,omitempty"`
	Idletimer int32 `json:"idletimer,omitempty"`
	ListenerDefaultShards string `json:"listener_default_shards,omitempty"`
	ListenerMultiQueue string `json:"listener_multi_queue,omitempty"`
	LuaBurstTimeout int32 `json:"lua_burst_timeout,omitempty"`
	LuaForcedYield int32 `json:"lua_forced_yield,omitempty"`
	LuaLogLoggers string `json:"lua_log_loggers,omitempty"`
	LuaLogStderr string `json:"lua_log_stderr,omitempty"`
	LuaMaxmem bool `json:"lua_maxmem,omitempty"`
	LuaServiceTimeout int32 `json:"lua_service_timeout,omitempty"`
	LuaSessionTimeout int32 `json:"lua_session_timeout,omitempty"`
	LuaTaskTimeout int32 `json:"lua_task_timeout,omitempty"`
	MaxChecksPerThread int32 `json:"max_checks_per_thread,omitempty"`
	Maxaccept int32 `json:"maxaccept,omitempty"`
	Maxpollevents int32 `json:"maxpollevents,omitempty"`
	Maxrewrite int32 `json:"maxrewrite,omitempty"`
	MemoryHotSize int32 `json:"memory_hot_size,omitempty"`
	PatternCacheSize int32 `json:"pattern_cache_size,omitempty"`
	PeersMaxUpdatesAtOnce int32 `json:"peers_max_updates_at_once,omitempty"`
	Pipesize int32 `json:"pipesize,omitempty"`
	PoolHighFdRatio int32 `json:"pool_high_fd_ratio,omitempty"`
	PoolLowFdRatio int32 `json:"pool_low_fd_ratio,omitempty"`
	PtZeroCopyForwarding string `json:"pt_zero_copy_forwarding,omitempty"`
	QuicFrontendConnTxBuffersLimit int32 `json:"quic_frontend_conn_tx_buffers_limit,omitempty"`
	QuicFrontendMaxIdleTimeout int32 `json:"quic_frontend_max_idle_timeout,omitempty"`
	QuicFrontendMaxStreamsBidi int32 `json:"quic_frontend_max_streams_bidi,omitempty"`
	QuicMaxFrameLoss int32 `json:"quic_max_frame_loss,omitempty"`
	QuicRetryThreshold int32 `json:"quic_retry_threshold,omitempty"`
	QuicSocketOwner string `json:"quic_socket_owner,omitempty"`
	RcvbufBackend int32 `json:"rcvbuf_backend,omitempty"`
	RcvbufClient int32 `json:"rcvbuf_client,omitempty"`
	RcvbufFrontend int32 `json:"rcvbuf_frontend,omitempty"`
	RcvbufServer int32 `json:"rcvbuf_server,omitempty"`
	RecvEnough int32 `json:"recv_enough,omitempty"`
	RunqueueDepth int32 `json:"runqueue_depth,omitempty"`
	SchedLowLatency string `json:"sched_low_latency,omitempty"`
	SndbufBackend int32 `json:"sndbuf_backend,omitempty"`
	SndbufClient int32 `json:"sndbuf_client,omitempty"`
	SndbufFrontend int32 `json:"sndbuf_frontend,omitempty"`
	SndbufServer int32 `json:"sndbuf_server,omitempty"`
	SslCachesize int32 `json:"ssl_cachesize,omitempty"`
	SslCaptureBufferSize int32 `json:"ssl_capture_buffer_size,omitempty"`
	SslCtxCacheSize int32 `json:"ssl_ctx_cache_size,omitempty"`
	SslDefaultDhParam int32 `json:"ssl_default_dh_param,omitempty"`
	SslForcePrivateCache bool `json:"ssl_force_private_cache,omitempty"`
	SslKeylog string `json:"ssl_keylog,omitempty"`
	SslLifetime int32 `json:"ssl_lifetime,omitempty"`
	SslMaxrecord int32 `json:"ssl_maxrecord,omitempty"`
	SslOcspUpdateMaxDelay int32 `json:"ssl_ocsp_update_max_delay,omitempty"`
	SslOcspUpdateMinDelay int32 `json:"ssl_ocsp_update_min_delay,omitempty"`
	StickCounters int32 `json:"stick_counters,omitempty"`
	VarsGlobalMaxSize int32 `json:"vars_global_max_size,omitempty"`
	VarsProcMaxSize int32 `json:"vars_proc_max_size,omitempty"`
	VarsReqresMaxSize int32 `json:"vars_reqres_max_size,omitempty"`
	VarsSessMaxSize int32 `json:"vars_sess_max_size,omitempty"`
	VarsTxnMaxSize int32 `json:"vars_txn_max_size,omitempty"`
	ZlibMemlevel int32 `json:"zlib_memlevel,omitempty"`
	ZlibWindowsize int32 `json:"zlib_windowsize,omitempty"`
}
