/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Cookie struct {
	Attr []CookieAttr `json:"attr,omitempty"`
	Domain []CookieDomain `json:"domain,omitempty"`
	Dynamic bool `json:"dynamic,omitempty"`
	Httponly bool `json:"httponly,omitempty"`
	Indirect bool `json:"indirect,omitempty"`
	Maxidle int32 `json:"maxidle,omitempty"`
	Maxlife int32 `json:"maxlife,omitempty"`
	Name string `json:"name"`
	Nocache bool `json:"nocache,omitempty"`
	Postonly bool `json:"postonly,omitempty"`
	Preserve bool `json:"preserve,omitempty"`
	Secure bool `json:"secure,omitempty"`
	Type_ string `json:"type,omitempty"`
}
