/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Balance struct {
	Algorithm string `json:"algorithm"`
	HashExpression string `json:"hash_expression,omitempty"`
	HdrName string `json:"hdr_name,omitempty"`
	HdrUseDomainOnly bool `json:"hdr_use_domain_only,omitempty"`
	RandomDraws int32 `json:"random_draws,omitempty"`
	RdpCookieName string `json:"rdp_cookie_name,omitempty"`
	UriDepth int32 `json:"uri_depth,omitempty"`
	UriLen int32 `json:"uri_len,omitempty"`
	UriPathOnly bool `json:"uri_path_only,omitempty"`
	UriWhole bool `json:"uri_whole,omitempty"`
	UrlParam string `json:"url_param,omitempty"`
	UrlParamCheckPost int32 `json:"url_param_check_post,omitempty"`
	UrlParamMaxWait int32 `json:"url_param_max_wait,omitempty"`
}
