/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SiteFarms struct {
	Balance *Balance `json:"balance,omitempty"`
	Cond string `json:"cond,omitempty"`
	CondTest string `json:"cond_test,omitempty"`
	Forwardfor *Forwardfor `json:"forwardfor,omitempty"`
	Mode string `json:"mode,omitempty"`
	Name string `json:"name"`
	Servers []Server `json:"servers,omitempty"`
	UseAs string `json:"use_as"`
}
