/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Set a template to initialize servers with shared parameters.
type ServerTemplate struct {
	AgentAddr string `json:"agent-addr,omitempty"`
	AgentCheck string `json:"agent-check,omitempty"`
	AgentInter int32 `json:"agent-inter,omitempty"`
	AgentPort int32 `json:"agent-port,omitempty"`
	AgentSend string `json:"agent-send,omitempty"`
	Allow0rtt bool `json:"allow_0rtt,omitempty"`
	Alpn string `json:"alpn,omitempty"`
	Backup string `json:"backup,omitempty"`
	Check string `json:"check,omitempty"`
	CheckSendProxy string `json:"check-send-proxy,omitempty"`
	CheckSni string `json:"check-sni,omitempty"`
	CheckSsl string `json:"check-ssl,omitempty"`
	CheckAlpn string `json:"check_alpn,omitempty"`
	CheckProto string `json:"check_proto,omitempty"`
	CheckViaSocks4 string `json:"check_via_socks4,omitempty"`
	Ciphers string `json:"ciphers,omitempty"`
	Ciphersuites string `json:"ciphersuites,omitempty"`
	ClientSigalgs string `json:"client_sigalgs,omitempty"`
	Cookie string `json:"cookie,omitempty"`
	CrlFile string `json:"crl_file,omitempty"`
	Curves string `json:"curves,omitempty"`
	Downinter int32 `json:"downinter,omitempty"`
	ErrorLimit int32 `json:"error_limit,omitempty"`
	Fall int32 `json:"fall,omitempty"`
	Fastinter int32 `json:"fastinter,omitempty"`
	ForceSslv3 string `json:"force_sslv3,omitempty"`
	ForceTlsv10 string `json:"force_tlsv10,omitempty"`
	ForceTlsv11 string `json:"force_tlsv11,omitempty"`
	ForceTlsv12 string `json:"force_tlsv12,omitempty"`
	ForceTlsv13 string `json:"force_tlsv13,omitempty"`
	HealthCheckAddress string `json:"health_check_address,omitempty"`
	HealthCheckPort int32 `json:"health_check_port,omitempty"`
	InitAddr string `json:"init-addr,omitempty"`
	Inter int32 `json:"inter,omitempty"`
	LogBufsize int32 `json:"log-bufsize,omitempty"`
	LogProto string `json:"log_proto,omitempty"`
	Maintenance string `json:"maintenance,omitempty"`
	MaxReuse int32 `json:"max_reuse,omitempty"`
	Maxconn int32 `json:"maxconn,omitempty"`
	Maxqueue int32 `json:"maxqueue,omitempty"`
	Minconn int32 `json:"minconn,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	NoSslv3 string `json:"no_sslv3,omitempty"`
	NoTlsv10 string `json:"no_tlsv10,omitempty"`
	NoTlsv11 string `json:"no_tlsv11,omitempty"`
	NoTlsv12 string `json:"no_tlsv12,omitempty"`
	NoTlsv13 string `json:"no_tlsv13,omitempty"`
	NoVerifyhost string `json:"no_verifyhost,omitempty"`
	Npn string `json:"npn,omitempty"`
	Observe string `json:"observe,omitempty"`
	OnError string `json:"on-error,omitempty"`
	OnMarkedDown string `json:"on-marked-down,omitempty"`
	OnMarkedUp string `json:"on-marked-up,omitempty"`
	PoolLowConn int32 `json:"pool_low_conn,omitempty"`
	PoolMaxConn int32 `json:"pool_max_conn,omitempty"`
	PoolPurgeDelay int32 `json:"pool_purge_delay,omitempty"`
	Proto string `json:"proto,omitempty"`
	ProxyV2Options []string `json:"proxy-v2-options,omitempty"`
	Redir string `json:"redir,omitempty"`
	ResolveNet string `json:"resolve-net,omitempty"`
	ResolvePrefer string `json:"resolve-prefer,omitempty"`
	ResolveOpts string `json:"resolve_opts,omitempty"`
	Resolvers string `json:"resolvers,omitempty"`
	Rise int32 `json:"rise,omitempty"`
	SendProxy string `json:"send-proxy,omitempty"`
	SendProxyV2 string `json:"send-proxy-v2,omitempty"`
	SendProxyV2Ssl string `json:"send_proxy_v2_ssl,omitempty"`
	SendProxyV2SslCn string `json:"send_proxy_v2_ssl_cn,omitempty"`
	SetProxyV2TlvFmt *ServerParamsSetproxyv2tlvfmt `json:"set-proxy-v2-tlv-fmt,omitempty"`
	Shard int32 `json:"shard,omitempty"`
	Sigalgs string `json:"sigalgs,omitempty"`
	Slowstart int32 `json:"slowstart,omitempty"`
	Sni string `json:"sni,omitempty"`
	Socks4 string `json:"socks4,omitempty"`
	Source string `json:"source,omitempty"`
	Ssl string `json:"ssl,omitempty"`
	SslCafile string `json:"ssl_cafile,omitempty"`
	SslCertificate string `json:"ssl_certificate,omitempty"`
	SslMaxVer string `json:"ssl_max_ver,omitempty"`
	SslMinVer string `json:"ssl_min_ver,omitempty"`
	SslReuse string `json:"ssl_reuse,omitempty"`
	Stick string `json:"stick,omitempty"`
	TcpUt int32 `json:"tcp_ut,omitempty"`
	Tfo string `json:"tfo,omitempty"`
	TlsTickets string `json:"tls_tickets,omitempty"`
	Track string `json:"track,omitempty"`
	Verify string `json:"verify,omitempty"`
	Verifyhost string `json:"verifyhost,omitempty"`
	Weight int32 `json:"weight,omitempty"`
	Ws string `json:"ws,omitempty"`
	Fqdn string `json:"fqdn"`
	Id int32 `json:"id,omitempty"`
	NumOrRange string `json:"num_or_range"`
	Port int32 `json:"port,omitempty"`
	Prefix string `json:"prefix"`
}
