/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Enables logging of STDERR messages that the FastCGI application reports. It is an optional setting. By default, HAProxy Enterprise ignores STDERR messages.
type FcgiLogStderr struct {
	Address string `json:"address,omitempty"`
	Facility string `json:"facility,omitempty"`
	Format string `json:"format,omitempty"`
	Global bool `json:"global,omitempty"`
	Len int32 `json:"len,omitempty"`
	Level string `json:"level,omitempty"`
	Minlevel string `json:"minlevel,omitempty"`
	Sample *Sample `json:"sample,omitempty"`
}
