/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// One Map Entry
type MapEntry struct {
	Id string `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}
