/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// HAProxy reload
type Reload struct {
	Id string `json:"id,omitempty"`
	ReloadTimestamp int32 `json:"reload_timestamp,omitempty"`
	Response string `json:"response,omitempty"`
	Status string `json:"status,omitempty"`
}
