/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// HAProxy configuration transaction
type Transaction struct {
	Version int32 `json:"_version,omitempty"`
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
}
