/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProcessInfoItem struct {
	ActivePeers int32 `json:"active_peers,omitempty"`
	BusyPolling int32 `json:"busy_polling,omitempty"`
	BytesOutRate int32 `json:"bytes_out_rate,omitempty"`
	CompressBpsIn int32 `json:"compress_bps_in,omitempty"`
	CompressBpsOut int32 `json:"compress_bps_out,omitempty"`
	CompressBpsRateLim int32 `json:"compress_bps_rate_lim,omitempty"`
	ConnRate int32 `json:"conn_rate,omitempty"`
	ConnRateLimit int32 `json:"conn_rate_limit,omitempty"`
	ConnectedPeers int32 `json:"connected_peers,omitempty"`
	CumConns int32 `json:"cum_conns,omitempty"`
	CumReq int32 `json:"cum_req,omitempty"`
	CumSslConns int32 `json:"cum_ssl_conns,omitempty"`
	CurrConns int32 `json:"curr_conns,omitempty"`
	CurrSslConns int32 `json:"curr_ssl_conns,omitempty"`
	DroppedLogs int32 `json:"dropped_logs,omitempty"`
	FailedResolutions int32 `json:"failed_resolutions,omitempty"`
	HardMaxConn int32 `json:"hard_max_conn,omitempty"`
	IdlePct int32 `json:"idle_pct,omitempty"`
	Jobs int32 `json:"jobs,omitempty"`
	Listeners int32 `json:"listeners,omitempty"`
	MaxConn int32 `json:"max_conn,omitempty"`
	MaxConnRate int32 `json:"max_conn_rate,omitempty"`
	MaxPipes int32 `json:"max_pipes,omitempty"`
	MaxSessRate int32 `json:"max_sess_rate,omitempty"`
	MaxSock int32 `json:"max_sock,omitempty"`
	MaxSslConns int32 `json:"max_ssl_conns,omitempty"`
	MaxSslRate int32 `json:"max_ssl_rate,omitempty"`
	MaxZlibMemUsage int32 `json:"max_zlib_mem_usage,omitempty"`
	MemMaxMb int32 `json:"mem_max_mb,omitempty"`
	// Number of threads
	Nbthread int32 `json:"nbthread,omitempty"`
	Node string `json:"node,omitempty"`
	// Process id of the replying worker process
	Pid int32 `json:"pid,omitempty"`
	PipesFree int32 `json:"pipes_free,omitempty"`
	PipesUsed int32 `json:"pipes_used,omitempty"`
	PoolAllocMb int32 `json:"pool_alloc_mb,omitempty"`
	PoolFailed int32 `json:"pool_failed,omitempty"`
	PoolUsedMb int32 `json:"pool_used_mb,omitempty"`
	// Process number
	ProcessNum int32 `json:"process_num,omitempty"`
	// Number of spawned processes
	Processes int32 `json:"processes,omitempty"`
	// HAProxy version release date
	ReleaseDate string `json:"release_date,omitempty"`
	RunQueue int32 `json:"run_queue,omitempty"`
	SessRate int32 `json:"sess_rate,omitempty"`
	SessRateLimit int32 `json:"sess_rate_limit,omitempty"`
	SslBackendKeyRate int32 `json:"ssl_backend_key_rate,omitempty"`
	SslBackendMaxKeyRate int32 `json:"ssl_backend_max_key_rate,omitempty"`
	SslCacheLookups int32 `json:"ssl_cache_lookups,omitempty"`
	SslCacheMisses int32 `json:"ssl_cache_misses,omitempty"`
	SslFrontendKeyRate int32 `json:"ssl_frontend_key_rate,omitempty"`
	SslFrontendMaxKeyRate int32 `json:"ssl_frontend_max_key_rate,omitempty"`
	SslFrontendSessionReuse int32 `json:"ssl_frontend_session_reuse,omitempty"`
	SslRate int32 `json:"ssl_rate,omitempty"`
	SslRateLimit int32 `json:"ssl_rate_limit,omitempty"`
	Stopping int32 `json:"stopping,omitempty"`
	Tasks int32 `json:"tasks,omitempty"`
	TotalBytesOut int32 `json:"total_bytes_out,omitempty"`
	UlimitN int32 `json:"ulimit_n,omitempty"`
	Unstoppable int32 `json:"unstoppable,omitempty"`
	// HAProxy uptime in s
	Uptime int32 `json:"uptime,omitempty"`
	// HAProxy version string
	Version string `json:"version,omitempty"`
	ZlibMemUsage int32 `json:"zlib_mem_usage,omitempty"`
}
