/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConfigStickTable struct {
	Expire int32 `json:"expire,omitempty"`
	Keylen int32 `json:"keylen,omitempty"`
	Nopurge bool `json:"nopurge,omitempty"`
	Peers string `json:"peers,omitempty"`
	Size int32 `json:"size,omitempty"`
	Srvkey string `json:"srvkey,omitempty"`
	Store string `json:"store,omitempty"`
	Type_ string `json:"type,omitempty"`
	WriteTo string `json:"write_to,omitempty"`
}
