/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A file containing one or more SSL/TLS certificates and keys
type SslCertificate struct {
	Algorithm string `json:"algorithm,omitempty"`
	AuthorityKeyId string `json:"authority_key_id,omitempty"`
	Description string `json:"description,omitempty"`
	Domains string `json:"domains,omitempty"`
	File string `json:"file,omitempty"`
	IpAddresses string `json:"ip_addresses,omitempty"`
	Issuers string `json:"issuers,omitempty"`
	NotAfter time.Time `json:"not_after,omitempty"`
	NotBefore time.Time `json:"not_before,omitempty"`
	Serial string `json:"serial,omitempty"`
	Sha1FingerPrint string `json:"sha1_finger_print,omitempty"`
	Sha256FingerPrint string `json:"sha256_finger_print,omitempty"`
	// File size in bytes.
	Size int32 `json:"size,omitempty"`
	StorageName string `json:"storage_name,omitempty"`
	Subject string `json:"subject,omitempty"`
	SubjectAlternativeNames string `json:"subject_alternative_names,omitempty"`
	SubjectKeyId string `json:"subject_key_id,omitempty"`
}
