/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplane

type GlobalFiftyOneDegreesOptions struct {
	CacheSize         int32  `json:"cache_size,omitempty"`
	DataFile          string `json:"data_file,omitempty"`
	PropertyNameList  string `json:"property_name_list,omitempty"`
	PropertySeparator string `json:"property_separator,omitempty"`
}
