/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// One SSL/TLS certificate
type SslCertEntry struct {
	Algorithm string `json:"algorithm,omitempty"`
	ChainIssuer string `json:"chain_issuer,omitempty"`
	ChainSubject string `json:"chain_subject,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	NotAfter string `json:"not_after,omitempty"`
	NotBefore string `json:"not_before,omitempty"`
	Serial string `json:"serial,omitempty"`
	Sha1FingerPrint string `json:"sha1_finger_print,omitempty"`
	Status string `json:"status,omitempty"`
	StorageName string `json:"storage_name,omitempty"`
	Subject string `json:"subject,omitempty"`
	SubjectAlternativeNames []string `json:"subject_alternative_names,omitempty"`
}
