/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Settings related to a cluster.
type ClusterSettings struct {
	BootstrapKey string `json:"bootstrap_key,omitempty"`
	Cluster *ClusterControllerInformation `json:"cluster,omitempty"`
	Mode string `json:"mode,omitempty"`
	Status string `json:"status,omitempty"`
}
