/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// General API, OS and hardware information
type Info struct {
	Api *InfoApi `json:"api,omitempty"`
	System *InfoSystem `json:"system,omitempty"`
}
