/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplane

// HAProxy TCP Request Rule configuration (corresponds to tcp-request)
type TcpRequestRule struct {
	Action               string `json:"action,omitempty"`
	BandwidthLimitLimit  string `json:"bandwidth_limit_limit,omitempty"`
	BandwidthLimitName   string `json:"bandwidth_limit_name,omitempty"`
	BandwidthLimitPeriod string `json:"bandwidth_limit_period,omitempty"`
	CaptureLen           int32  `json:"capture_len,omitempty"`
	CaptureSample        string `json:"capture_sample,omitempty"`
	Cond                 string `json:"cond,omitempty"`
	CondTest             string `json:"cond_test,omitempty"`
	Expr                 string `json:"expr,omitempty"`
	GptValue             string `json:"gpt_value,omitempty"`
	Index                int32  `json:"index"`
	LogLevel             string `json:"log_level,omitempty"`
	LuaAction            string `json:"lua_action,omitempty"`
	LuaParams            string `json:"lua_params,omitempty"`
	MarkValue            string `json:"mark_value,omitempty"`
	NiceValue            int32  `json:"nice_value,omitempty"`
	PriorityType         string `json:"priority_type,omitempty"`
	ResolveProtocol      string `json:"resolve_protocol,omitempty"`
	ResolveResolvers     string `json:"resolve_resolvers,omitempty"`
	ResolveVar           string `json:"resolve_var,omitempty"`
	ScIdx                string `json:"sc_idx,omitempty"`
	ScIncId              string `json:"sc_inc_id,omitempty"`
	ScInt                int32  `json:"sc_int,omitempty"`
	ServerName           string `json:"server_name,omitempty"`
	ServiceName          string `json:"service_name,omitempty"`
	SpoeEngineName       string `json:"spoe_engine_name,omitempty"`
	SpoeGroupName        string `json:"spoe_group_name,omitempty"`
	SwitchModeProto      string `json:"switch_mode_proto,omitempty"`
	Timeout              int32  `json:"timeout,omitempty"`
	TosValue             string `json:"tos_value,omitempty"`
	TrackKey             string `json:"track_key,omitempty"`
	TrackStickCounter    int32  `json:"track_stick_counter,omitempty"`
	TrackTable           string `json:"track_table,omitempty"`
	Type_                string `json:"type"`
	VarFormat            string `json:"var_format,omitempty"`
	VarName              string `json:"var_name,omitempty"`
	VarScope             string `json:"var_scope,omitempty"`
}
