/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplane

// HAProxy TCP Response Rule configuration (corresponds to tcp-response)
type TcpResponseRule struct {
	Action               string `json:"action,omitempty"`
	BandwidthLimitLimit  string `json:"bandwidth_limit_limit,omitempty"`
	BandwidthLimitName   string `json:"bandwidth_limit_name,omitempty"`
	BandwidthLimitPeriod string `json:"bandwidth_limit_period,omitempty"`
	Cond                 string `json:"cond,omitempty"`
	CondTest             string `json:"cond_test,omitempty"`
	Expr                 string `json:"expr,omitempty"`
	Index                int32  `json:"index"`
	LogLevel             string `json:"log_level,omitempty"`
	LuaAction            string `json:"lua_action,omitempty"`
	LuaParams            string `json:"lua_params,omitempty"`
	MarkValue            string `json:"mark_value,omitempty"`
	NiceValue            int32  `json:"nice_value,omitempty"`
	ScExpr               string `json:"sc_expr,omitempty"`
	ScId                 int32  `json:"sc_id,omitempty"`
	ScIdx                int32  `json:"sc_idx,omitempty"`
	ScInt                int32  `json:"sc_int,omitempty"`
	SpoeEngine           string `json:"spoe_engine,omitempty"`
	SpoeGroup            string `json:"spoe_group,omitempty"`
	Timeout              int32  `json:"timeout,omitempty"`
	TosValue             string `json:"tos_value,omitempty"`
	Type_                string `json:"type"`
	VarName              string `json:"var_name,omitempty"`
	VarScope             string `json:"var_scope,omitempty"`
}
